// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.umbook.server.domain;

import com.umbook.server.domain.Foto;

privileged aspect ComentarioFoto_Roo_JavaBean {
    
    public Foto ComentarioFoto.getFoto() {
        return this.foto;
    }
    
    public void ComentarioFoto.setFoto(Foto foto) {
        this.foto = foto;
    }
    
}
