// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.umbook.server.domain;

import com.umbook.server.domain.Album;

privileged aspect ComentarioAlbum_Roo_JavaBean {
    
    public Album ComentarioAlbum.getAlbum() {
        return this.album;
    }
    
    public void ComentarioAlbum.setAlbum(Album album) {
        this.album = album;
    }
    
}
